CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64),
    email VARCHAR(64),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32),
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS locations (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    lat FLOAT,
    lon FLOAT,
    CONSTRAINT pk_location PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS events (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    annotation VARCHAR(1024),
    title VARCHAR(128),
    category_id INT,
    confirmed_requests INT,
    created_on TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_DATE,
    description VARCHAR(1024),
    event_date TIMESTAMP WITHOUT TIME ZONE,
    initiator_id INT,
    location_id INT,
    paid BOOLEAN,
    participant_limit INT,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(32),
    request_moderation BOOLEAN,
    views INT DEFAULT 0,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_events_users FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT fk_events_location FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    event_id INT,
    requester_id INT,
    status VARCHAR(32),
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_DATE,
    CONSTRAINT pk_event_requests PRIMARY KEY (id),
    CONSTRAINT fk_event_requests_events FOREIGN KEY (event_id) REFERENCES categories (id),
    CONSTRAINT fk_event_requests_users FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    pinned BOOLEAN,
    title VARCHAR(128),
    CONSTRAINT pk_compilation PRIMARY KEY (id),
    CONSTRAINT UQ_TITTLE UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_event (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    compilation_id INT,
    event_id INT,
    CONSTRAINT pk_compilation_event PRIMARY KEY (id),
    CONSTRAINT fk_compilation_event_compilation FOREIGN KEY (compilation_id) REFERENCES locations (id),
    CONSTRAINT fk_compilation_event_events FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT UQ_COMPILATION_EVENT UNIQUE (compilation_id, event_id)
);

